### PR TITLE
[WIP] Embedded PDF creation using Tectonic

### PR DESCRIPTION
**Pull request by vitSkalicky**
Added ability to create PDF files directly without the need for an external LaTeX compiler.

Added `pdf` format for `.pdf` file extension, which compiles the file into LaTeX just like `tex` format, but then processes in output using the [Tectonic library](https://crates.io/crates/tectonic) into a pdf and saves the resulting file into the output directory. [Tectonic](https://tectonic-typesetting.github.io/) is LaTeX compiler embedded directly in Bard's binary, which makes it easier to use for non technical users. 

However, this means that compilation also requires compilation of the entire Tectonic LaTeX engine, which has major parts written in C, so building isn't as simple as pure Rust. On windows, for example, it requires Git and vcpkg. Therefore, it might be a good idea to make Tectonic opt-out using cargo features.

Also when there is a problem with compiling LaTeX into PDF, Tectonic returns an error, but my Rust skills are very limited and I was unable to propagate the message and details of the error to the user.

Summary:
- [X] Create PDF without external LaTeX installation
- [ ] Show a useful error to the user when converting LaTeX into PDF fails (help needed)
- [ ] Make Tectonic library a feature (on by default) (help needed)
- [ ] update examples and add documentation
- [ ] fix CI (help needed)

## Compilation

<details>
<summary>Windows</summary>

1. install rust
2. install git
3. clone bard
4. enter directory of bard
5. open the git shell
6. `cargo install cargo-vcpkg`
7. `cargo vcpkg build`
8. wait
9. wait
10.  wait (once it took 2960.09s)
12.  `export VCPKG_ROOT="${CARGO_TARGET_DIR:-$(pwd)/target}/vcpkg"`
13.  `export RUSTFLAGS='-Ctarget-feature=+crt-static'  # Windows only`
14.  `export TECTONIC_DEP_BACKEND=vcpkg`
18.  `cargo build --release`
19.  done!

</details>

<details><summary>Linux</summary>

1. install rust
2. install git
3. install pkg-config
4. clone bard
5. enter directory of bard
6. open shell
7. `cargo  build --release`
8. if it fails, read the error message, install the library it says it is missing and go to step 7
9. done

</details>

### CODE REVIEW

**Comment by vojtechkral** [comment]
Hi. This is interesting stuff. I originally very much wanted to do something like this, but Tectonic wasn't mature enough at the time. Nice to see it could work these days.

> Therefore, it might be a good idea to make Tectonic opt-out using cargo features.

Yes, in fact I would prefer it to be _opt-in_ rather than opt-out, since it's a pretty large depencency. I could make CI provide Windows binaries with Tectonic turned on, since this makes sense the most on Windows.

> Also when there is a problem with compiling LaTeX into PDF, Tectonic returns an error, but my Rust skills are very limited and I was unable to propagate the message and details of the error to the user.

That's ok I can fix this. I'll check it out at some point this week.

Thanks!

**Comment by vojtechkral** [comment]
Hi.
I've reviewed this as well as tectonic and its build process in general, and I've decided not to merge this or integrate tectonic at this time.
The reasons for this are:
- I'm trying to finalize the 2.0 release of bard and this would be a fundamental change from a Rust-only to a Rust-with-C++ project, making building and testing a lot more complex. The project is not in a good stage to do this at the moment.
- The way outputs and post-processing are done at the moment doesn't go well together with tectonic integration, for example, you couldn't set up bard project to use TexLive on Linux and Tectonic on Windows. Sorted ToC would also not work anymore.

I will first (as part of 2.0) refactor the way outputs and post-processing is done, I want to decouple it from project definition and make bard look up TeX automatically. After 2.0 we can look into tectonic integration again, it should be easier by then.

LMK if you have any questions. Thanks!

**Comment by vitSkalicky** [comment]
Ok, I understand - I will keep using my fork until 2.0 with tectonic is ready as I need Bard to be usable by my friends without installing whole TeXlive, etc.

BTW, do could you help me with getting more useful error from Tectonic as mentioned in the original post?

**Comment by vojtechkral** [comment]
@vitSkalicky 
Out of curiosity, what OS do your friends use?
I recently started testing on Windows a bit more and noticed that the default bard latex processing indirectly requires Perl, which sucks. I plan to remove this problem so that on Windows it should be enough to install [MikTex](https://miktex.org/).

**Comment by vitSkalicky** [comment]
They use Windows, that's why I want latex processing to be embedded in the bard.exe executable.

**Comment by vojtechkral** [comment]
Hi.

For the 2.0 version I had refactored outputs and TeX processing quite a bit. The post-processing steps have been removed and `bard` now looks up TeX distro and calls it automatically (although this can be customized).

After this, tectonic integration could fit a lot better. I have implemented it as an optional feature named `tectonic` (build wich `--features tectonic`), the implementation is now merged in `main`. It is a lot different, mostly 1) to keep tectonic in a subprocess rather than calling into it directly, for better isolation, and 2) to keep the alpha-sorted ToC option.

I don't think it will be possible to build with tectonic in the CI, because the build artifacts are very large, especially on Windows (almost 7GB), so I will probably provide manually built binaries with tectonic enabled for tagged releases. I will only provide them for Windows, on Linux only non-tectonic binaries will be provided (but you can still build with tectonic yourself if you want).

**Comment by vojtechkral** [comment]
This will be part of the 2.0 release.

At the moment, all these changes and features are not documented - that remains the last work needed before 2.0 can be finalized.

**Pull request closed without merging**
