### PR TITLE
Fixed typo in "whisky" filename

### PR DESCRIPTION
**Pull request by 0atman**
This is a trivial typo. :+1:

### CODE REVIEW

**Comment by 0atman** [comment]
@vojtechkral I searched for something to fix so I could say THANK YOU! This exactly the project I've been searching for,to build my own songbook for years! (Starting it now https://github.com/0atman/namtao-songbook)

**Comment by vojtechkral** [comment]
Ha, good catch, thanks! :slightly_smiling_face: 
However, the filename also need fixing in the `examples/bard.toml` file, do you want to include that in the PR?

**Comment by vojtechkral** [comment]
I should probably figure out a way to test this in the CI...

**Comment by 0atman** [comment]
Done!

**Comment by vojtechkral** [comment]
Merged. Thanks for the fix and glad you like _bard_ :)

**Comment by 0atman** [comment]
Thanks for making it! :grin:

**Pull request merged**
